#!/usr/bin/env python3
"""
Appendix I - the AI governance map, generated from a real capstone run.

Every row is produced by labs/chapter-13-assembling-aegis/governance/report.py
from one hostile incident through AegisV12. Nothing in the appendix is typed by
hand, so a term that stops being true cannot survive in print.

    python tools/make_governance_appendix.py            # rewrite docs/appendix-i-governance-map.md
    python tools/make_governance_appendix.py --check    # exit 1 if the committed file drifted or a term fails

Two values vary per run and are normalised before writing: the trace_id and the
measured latency. Everything else is deterministic on the mock tier.
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "labs", "chapter-13-assembling-aegis"))
from governance import report as gov                                        # noqa: E402

OUT = os.path.join(REPO, "docs", "appendix-i-governance-map.md")


def _normalise(text: str) -> str:
    text = re.sub(r"inc-[0-9a-f]{8}", "inc-<trace_id>", text)
    return re.sub(r"latency [\d.]+ ms", "latency <measured> ms", text)


def render() -> str:
    system, run = gov.run_capstone()
    rows = gov.governance_report(run, system)
    inv = gov.inventory(system)
    held = sum(r["holds"] for r in rows)

    out = ["# Appendix I - The Governance Map",
           "",
           "*Generated by `tools/make_governance_appendix.py` from one run of the assembled system.",
           "Do not edit by hand; CI regenerates it and fails on drift.*",
           "",
           "Every AI-governance checklist uses the same ten terms. None of them is a chapter in this book,",
           "because each one is the name for a mechanism a chapter already built and a demo already tests.",
           "The table below was not written; it was produced by running the capstone on a hostile alert",
           "and asking, for each term, which code proves it and what that code printed.",
           "",
           f"**{held}/{len(rows)} terms hold on the run that generated this page.**",
           "",
           "| # | Term | Chapter(s) | Mechanism | Evidence from the run |",
           "|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        out.append(f"| {i} | {r['term']} | {r['chapter']} | `{r['mechanism']}` | {r['evidence']} |")

    out += ["",
            "## The two terms the book had to add",
            "",
            "Eight of the ten were already load-bearing code. Two were only implied, and an implied control",
            "is not a control. Both live in `labs/chapter-13-assembling-aegis/governance/report.py`.",
            "",
            "### AI Inventory - `inventory()`",
            "",
            "Derived from the code that runs, never typed in: if a tool's signature or docstring changes,",
            "its fingerprint changes and this page drifts.",
            "",
            "```"]
    out.append(f"agents       : {inv['agents']}")
    for name, meta in inv["tools"].items():
        out.append(f"tool         : {name:<17} fingerprint={meta['fingerprint']}  world_changing={meta['world_changing']}")
    out.append(f"model tier   : {inv['model_tier']}  (card on file: {inv['model_card']})")
    out.append(f"stages       : {' -> '.join(inv['stages'])}")
    out += ["```",
            "",
            f"### Model Cards - `MODEL_CARDS` (verified {gov.CARDS_VERIFIED}, stale after {gov.STALE_AFTER_DAYS} days)",
            "",
            "A card is a dated claim, exactly like a price in Chapter 12. The field that matters most is",
            "`decides`, and for every tier in this book the answer is the same.",
            ""]
    for tier, card in gov.MODEL_CARDS.items():
        out.append(f"**{tier}**")
        out.append("")
        for k, v in card.items():
            out.append(f"- {k}: {v}")
        out.append("")
    out += ["## How to read this in your own system",
            "",
            "Run `python labs/chapter-13-assembling-aegis/governance/report.py --check` against your alerts.",
            "A term that fails is not a governance gap to document; it is a test that found something.",
            "The checklist is the output of the system, not an input to it.",
            ""]
    return _normalise("\n".join(out))


def main(argv: list) -> int:
    text = render()
    if "--check" in argv:
        if not os.path.exists(OUT):
            print(f"FAILED: {os.path.relpath(OUT, REPO)} missing; run without --check to generate it")
            return 1
        committed = open(OUT).read()
        if committed != text:
            print(f"FAILED: {os.path.relpath(OUT, REPO)} drifted from the code; regenerate and commit")
            return 1
        if "**10/10 terms hold" not in text:
            print("FAILED: not every governance term holds on the generating run")
            return 1
        print("appendix I  ok  matches a fresh run; 10/10 terms hold")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(OUT, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
